import styles from "./page.module.css";
import img1 from "@/app/assets/games.png";
import img2 from "../assets/store.png";
import img3 from "../assets/shop.png";
import img4 from "../assets/ecommerce.png";
import img5 from "../assets/todo.png";
import img6 from "../assets/moxtilshows.png";
import { CiShoppingTag } from "react-icons/ci";

export const metadata = {
  title: "Moxtil - Projects",
  description: "Generated by create next app",
};
import Image from "next/image";
import Link from "next/link";
const websites = [
  {
    id: 1,
    img: img1,
    title: "Moxtil Games",
    url: "https://moxtilgames.netlify.app",
    desc: "Wide Gaming Website Consists of Muliple Pages , With A Dynamic Search For Games , Friends . Involves Params To Look For Any Game's Full Details",
    tags: [
      {
        id: 1,
        name: "Next JS",
      },
    ],
  },
  {
    id: 2,
    title: "Moxtil Store",
    url: "https://moxtilstore.netlify.app",
    desc: "E-Commerce Website consists of 5 pages , containing Home , Shopping , Features , Discounts and Contact Pages , Made with react js , use-params , react router and use-cart to add products and save them in local storage",
    img: img2,
    tags: [
      {
        id: 1,
        name: "React JS",
      },
      {
        id: 2,
        name: "Tailwind CSS",
      },
    ],
  },
  {
    id: 3,
    title: "Moxtil Shop",
    url: "https://moxtilshop.netlify.app",
    img: img3,
    desc: "E-Commerce Website consists of 4 pages , containing Home , Shopping , Offers and Contact Pages , Made with react js , useParams , react router and useCart to add products and save them in local storage .",
    tags: [{ id: 1, name: "React JS" }],
  },
  {
    id: 4,
    title: "Moxtil E-Commerce",
    url: "https://moxtilecommerce.netlify.app",
    desc: "E-Commerce Website consists of 4 pages , containing Home , Shopping , Offers and Contact Pages , Made with react js , useParams , react router and useCart to add products and save them in local storage .",
    img: img4,
    tags: [
      {
        id: 1,
        name: "React JS",
      },
      { id: 2, name: "Tailwind CSS" },
    ],
  },
  {
    id: 5,
    title: "Moxtil To Do List",
    url: "https://moxtiltodolist.netlify.app",
    desc: "To Do List Application With The Local Storage Saving , Mark As Done or Active Todo Website",
    img: img5,
    tags: [
      {
        id: 1,
        name: "JavaScript",
      },
    ],
  },
  {
    id: 6,
    title: "Moxtil Shows",
    url: "https://moxtilshows.netlify.app",
    desc: "TV Shows / Movies Search Application Contains Each Show's Details",
    img: img6,
    tags: [
      {
        id: 1,
        name: "Next JS",
      },
    ],
  },
];
export default function page() {
  return (
    <div className={styles.mainContainer}>
      <div className={styles.container}>
        {websites.map((we) => {
          return (
            <Link href={we.url} key={we.id} target="_blank">
              <Image src={we?.img} alt="Web" width={600} height={300} />
              <h3 style={{ padding: "10px" }}>{we.title}</h3>
              <p style={{ padding: "10px" }}>{we?.desc}</p>
              <div className={styles.tags}>
                {we.tags.map((t) => {
                  return (
                    <span key={t.id}>
                      <CiShoppingTag size={20} />
                      {t.name}
                    </span>
                  );
                })}
              </div>
            </Link>
          );
        })}
      </div>
    </div>
  );
}
