import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar/Navbar";

const montserrat = Montserrat({
  weight: ["400", "500", "600"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Moxtil - Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
        <Navbar />

        {children}
      </body>
    </html>
  );
}
