import Link from "next/link";
import styles from "./page.module.css";
import {
  FaHtml5,
  FaCss3Alt,
  FaBootstrap,
  FaReact,
  FaGithub,
} from "react-icons/fa";
import { IoLogoJavascript } from "react-icons/io5";
import { RiTailwindCssFill, RiNextjsFill } from "react-icons/ri";
export const metadata = {
  title: "Moxtil - Skills",
  description: "Generated by create next app",
};
export default function page() {
  return (
    <div className={styles.mainContainer}>
      <div className={styles.container}>
        <div className={styles.leftSide}>
          <h3>
            Favorite <span>Skills</span>
          </h3>
          <h1>My Skills</h1>
          <p>On the other hand, I possess skills in web development</p>
          <Link href={"/Projects"}>View Projects</Link>
        </div>
        <div className={styles.skills}>
          <div>
            <FaHtml5 color="orange" />
            <p>HTML 5</p>
          </div>
          <div>
            <FaCss3Alt color="#2f76ff" />
            <p>CSS 3</p>
          </div>
          <div>
            <IoLogoJavascript color="gold" />
            <p>JavaScript</p>
          </div>
          <div>
            <RiTailwindCssFill color="#4fa6ff" />
            <p>Tailwind CSS</p>
          </div>
          <div>
            <FaGithub />
            <p>Git & GitHub</p>
          </div>
          <div>
            <FaBootstrap color="#c047c0" />
            <p>Bootstrap</p>
          </div>
          <div>
            <FaReact color="#209eff" />
            <p>React JS</p>
          </div>
          <div>
            <RiNextjsFill />
            <p>Next JS</p>
          </div>
        </div>
      </div>
    </div>
  );
}
